toa_misc:
    defaults:
        _controller: "ToaMiscBundle:Default:ip"
    host:   ip.schwabbauer.eu
    path:   /
    schemes:  [ https ]

toa_welcome:
    resource: "@ToaWelcomeBundle/Controller/"
    type:     annotation
    prefix:   /
    schemes:  [ https ]

