toa_misc_ip:
    defaults:
        _controller: "ToaMiscBundle:Default:ip"
    host:   "ip.{tldomain}"
    path:   /
    requirements:
        tldomain: "%tldomains%"

toa_welcome:
    resource: "@ToaWelcomeBundle/Controller/"
    type:     annotation
    prefix:   /
    schemes:  [ https ]

