toa_misc_ip:
    defaults:
        _controller: "ToaMiscBundle:Default:ip"
    host:     "ip.{_domain}"
    path:   /
    requirements:
        _domain: "%domain1%|%domain2%"

toa_welcome_schwabbauer:
    resource: "@ToaWelcomeBundle/Controller/SchwabbauerController.php"
    type:     annotation
    prefix:   /schwabbauer

toa_welcome_fuchluchs:
    resource: "@ToaWelcomeBundle/Controller/FuchsLuchsController.php"
    type:     annotation
    host:     "{_domain}"
    prefix:   /
    requirements:
        _domain: "%domain2%|www.%domain2%"
