toa_misc:
    resource: "@ToaMiscBundle/Controller/"
    type:     annotation
    prefix:   /misc

toa_welcome:
    resource: "@ToaWelcomeBundle/Controller/"
    type:     annotation
    prefix:   /

