toa_misc_ip:
    defaults:
        _controller: "ToaMiscBundle:Default:ip"
    host:     "{_subdomain}.{_domain}"
    path:   /
    requirements:
        _domain: "%domains%"
        _subdomain: ip

toa_welcome:
    resource: "@ToaWelcomeBundle/Controller/"
    type:     annotation
    prefix:   /
    schemes:  [ https ]
