jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        oauth:
            id: oauth.user.provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        secured_area:
            anonymous: ~
            pattern: ^/
            oauth:
                resource_owners:
                    google:         google_login
                login_path:         hwi_oauth_connect
                failure_path:       hwi_oauth_connect
                oauth_user_provider:
                    service: oauth.user.provider
            logout:
                path: toa_welcome_security_logout
                target: toa_welcome_default_default

    access_control:
        - { path: ^/(login|redirect|connect), role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/*, role: ROLE_USER }
