stof_doctrine_extensions:
    orm:
        default:
            timestampable: true
            sluggable: true
            softdeleteable: true

doctrine:
    orm:
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
    